### ISSUE TITLE
Can't bind to 'x' since it isn't a known native property

### ISSUE THREAD

**Issue by cioraneanu** [valor-software/ng2-table#196]
I'm having problems trying to get the demo to work. 
1. I've installed the module via:
   `npm i ng2-table --save`
2. I've added the entries in systemjs.config.js for the map and package fields

```
var map = {
    ...
    'ng2-table':                    'node_modules/ng2-table'
  };

  var packages = {
   ...
    'ng2-table':                    { defaultExtension: 'js' }
  };
```
1. Copied the html and ts from here: http://valor-software.com/ng2-table/

When loading the created component I get the following error:

> Can't bind to 'totalItems' since it isn't a known native property

What am I missing?

**Comment by pulankit** [comment]
@cioraneanu  Make sure you have installed ng2-bootsrap and added the same to maps and  packages in systemjs.config.js

**Comment by stephenad** [comment]
Hi Folks,

Still working on this NG2-table but getting the errors below and not sure how to resolve these any advice appreciated.

`vendor.bundle.js:237581 Unhandled Promise rejection: Template parse errors:
Can't bind to 'active' since it isn't a known property of 'ng-table'.
1. If 'ng-table' is an Angular component and it has 'active' input, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("="onNewUserChangeTable(newuserConfig)"
                        (cellClicked)="onCellClick($event)" [ERROR ->][active]="selectedNewUserRow"
                        [rows]="newuserRows" [columns]="newuserColumns"): NEWAdminUserTableComponent@38:60
Can't bind to 'links' since it isn't a known property of 'ng-table'.
1. If 'ng-table' is an Angular component and it has 'links' input, then verify that it is part of this module.
2. If 'ng-table' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("tive]="selectedNewUserRow"
                        [rows]="newuserRows" [columns]="newuserColumns" [ERROR ->][links]="newuserLinks" 
                        (editClicked)="onEditClicked($event)"
             "): NEWAdminUserTableComponent@39:72
Can't bind to 'options' since it isn't a known property of 'ng-select'.
1. If 'ng-select' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ng-select' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 (">
                             <div class="col-sm-8"> 
                                <ng-select [ERROR ->][options]="customersToSelect" formControlName="CustomerID" placeholder="Select Customer Name" [disabl"): NEWAdminUserTableComponent@261:43
Can't bind to 'allowClear' since it isn't a known property of 'ng-select'.
1. If 'ng-select' is an Angular component and it has 'allowClear' input, then verify that it is part of this module.
2. If 'ng-select' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("Select" formControlName="CustomerID" placeholder="Select Customer Name" [disabled]="isReadOnlyForm" [ERROR ->][allowClear]="true" 
                                     (deselected)="onCustomerDeselected($event)"): NEWAdminUserTableComponent@261:165
'ng-select' is not a known element:
1. If 'ng-select' is an Angular component, then verify that it is part of this module.
2. If 'ng-select' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("Name</label>
                             <div class="col-sm-8"> 
                                [ERROR ->]<ng-select [options]="customersToSelect" formControlName="CustomerID" placeholder="Select Customer Na"): NEWAdminUserTableComponent@261:32 ; `

Please can someone advise how to either troubleshoot or resolve these errors, 

Thanks in advance
Andy
